app/urls.py
from django.urls import path
from .views import *


app_name = "app"
urlpatterns = [
    path('', Home.as_view(), name="home"),
    path('search/', SearchResultsView.as_view(), name="search_results"),
	path('events/<slug:slug>/', EventDetailView.as_view(), name='event_detail'),
    path('events/create/new', EventCreate.as_view(), name='event_create'),
    path('events/update/<slug:slug>/', EventUpdate.as_view(), name='event_update'),
    path('events/delete/<slug:slug>/', EventDelete.as_view(), name='event_delete'),
    path('events/category/<slug:slug>/', category_details, name="category")
]

events/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import views as user_views
from app import views as api_view
# from rest_framework.


admin.site.site_header = "Events Admin"
admin.site.site_title = "Events Admin Portal"
admin.site.index_title = "Welcome To Events Administration Backend"

urlpatterns = [

    path('admin/', admin.site.urls),
    path('api/events/', api_view.EventApiList.as_view()),
    path('api/users/', api_view.UsersApiList.as_view()),
    path('api/events/<slug:slug>/', api_view.EventApiDetail.as_view()),
    path('', include("app.urls")),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.display_profile, name='profile'),
    path('profile/<slug:slug>/', user_views.DisplayProfile.as_view(), name='profile-detail'),
    path('edit_profile/', user_views.profile, name='edit_profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('activate/<slug:uidb64>/<slug:token>)/', user_views.activate_link, name='activate'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from PIL import Image


class Hashtag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50, unique=True, null=True, blank=True)

    def __str__(self):
        return self.name


def get_flyer(instance, filename):
    title = instance.title
    slug = slugify(title)
    return "flyers/{}/dukeevents_{}".format(slug, filename)


class State(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class FeaturedEvent(models.Model):
    name = models.CharField(max_length=50, null=True)
    slug = models.SlugField(max_length=50, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Featured Event"
        verbose_name_plural = "Featured Events"

    def _get_unique_slug(self):
        slug = slugify(self.name)
        unique_slug = slug
        num = 1
        while Event.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)


class Event(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=100, null=True)
    flyer = models.ImageField(upload_to=get_flyer, null=True, blank=True)
    description = models.TextField(max_length=500, null=True, blank=True)
    date_posted = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    category = models.ForeignKey(Hashtag, on_delete=models.CASCADE, null=True, blank=True)
    venue = models.CharField(max_length=200, null=True)
    state = models.ForeignKey(State, on_delete=models.CASCADE, null=True)
    feat = models.ForeignKey(FeaturedEvent, on_delete=models.CASCADE, null=True, blank=True)
    start_date = models.DateField(null=True, editable=True, blank=True)
    end_date = models.DateField(editable=True, null=True)
    start_time = models.TimeField(null=True)
    end_time = models.TimeField(null=True)
    slug = models.SlugField(max_length=100, null=True, blank=True, unique=True)
    approved = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def _get_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        num = 1
        while Event.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)

        img = Image.open(self.flyer.path)

        if img.height > 896 or img.width > 640:
            output_size = (640, 896)
            img.thumbnail(output_size)
            img.save(self.flyer.path)

    class Meta:
        verbose_name_plural = "Events"


class TicketType(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    amount = models.FloatField(null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Ticket"
        verbose_name_plural = "Tickets"


class Emails(models.Model):
    email_add = models.EmailField(null=True)

    def __str__(self):
        return self.email_add

app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>
	<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Favicon-->
	<link rel="shortcut icon" href="{% static 'app/img/fav.png' %}">
	<!-- Author Meta -->
	<meta name="author" content="codepixer">
	<!-- Meta Description -->
	<meta name="description" content="">
	<!-- Meta Keyword -->
	<meta name="keywords" content="">
	<!-- meta character set -->
	<meta charset="UTF-8">
	<!-- Site Title -->
	<title>Ruft Blog</title>

	<link href="https://fonts.googleapis.com/css?family=Roboto:400,500|Rubik:500" rel="stylesheet">
	<!--
			CSS
			============================================= -->
	<link rel="stylesheet" href="{% static 'app/css/linearicons.css' %}">
	<link rel="stylesheet" href="{% static 'app/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'app/css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'app/css/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static 'app/css/nice-select.css' %}">
	<link rel="stylesheet" href="{% static 'app/css/animate.min.css' %}">
	<link rel="stylesheet" href="{% static 'app/css/owl.carousel.css' %}">
	<link rel="stylesheet" href="{% static 'app/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'users/login_controller.css/' %}">
</head>

<body>
	<!--================ Start header Top Area =================-->
	<section class="header-top">
		<div class="container box_1170">
			<div class="row align-items-center justify-content-between">
				<div class="col-lg-6 col-md-6 col-sm-6">
					<a href="{% url 'app:home' %}" class="logo">
						<img src="{% static 'app/img/logo.png' %}" alt="">
					</a>
				</div>
                <form action="{% url 'app:search_results' %}" method="get">
				<div class="form-group">
						<input name="q" type="text" class="form-control" id="searchbar" placeholder="Search...">
				</div>
                </form>
			</div>
		</div>
	</section>

    {#            <input name="q" type="text" placeholder="Search...">#}
{#            <form action="{% url 'app:search_results' %}" method="get">#}
	<!--================ End header top Area =================-->

	<!-- Start header Area -->
	<header id="header">
		<div class="container box_1170 main-menu">
			<div class="row align-items-center justify-content-center d-flex">
				<nav id="nav-menu-container">
					<ul class="nav-menu">
						<li class="menu-active"><a href="{% url 'app:home' %}">Home</a></li>
						{% if user.is_authenticated %}<li><a href="{% url 'app:event_create' %}">Create Event</a></li>
                        <li><a href="{% url 'logout' %}">Logout</a></li>
                        <li><a href="{% url 'profile' %}">Profile</a></li>
                        {% else %}<li><a href="{% url 'login' %}">Login</a></li>
                        {% endif %}

						<li class="menu-has-children"><a href="">Pages</a>
							<ul>{% for category in object_list %}
								<li>{{ category.name }}</li>{% endfor %}
							</ul>
						</li>
						<li class="menu-has-children"><a href="">Blog</a>
							<ul>
								<li><a href="blog-details.html">Blog Details</a></li>
							</ul>
						</li>
						<li><a href="contact.html">Contact</a></li>
					</ul>
				</nav>
			</div>
		</div>

		<div class="search_input" id="search_input_box">
			<div class="container box_1170">
				<form class="d-flex justify-content-between">
					<input type="text" class="form-control" id="search_input" placeholder="Search Here">
					<button type="submit" class="btn"></button>
					<span class="lnr lnr-cross" id="close_search" title="Close Search"></span>
				</form>
			</div>
		</div>
	</header>
	<!-- End header Area -->
    	<section class="top-stories-area">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="owl-carousel active-stories-carousel">
						<!-- single stories carousel -->{% for event in ads %}
						<div class="single-stories-carousel d-flex align-items-center">
							<div class="stories-thumb">
								<img class="img-fluid" src="{{ event.flyer.url }}" alt="">
							</div>
							<div class="stories-details">
								<h6><a href="{% url 'app:event_detail' event.slug %}">{{ event.title }}</a></h6>
								<p>{{ event.end_date }}</p>
							</div>
						</div>{% endfor %}

					</div>
				</div>
			</div>
		</div>
	</section>

{% block content %}
{% endblock content %}

<!-- start footer Area -->
	<footer class="footer-area section-gap">
		<div class="container box_1170">
			<div class="row">
				<div class="col-lg-3 col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6 class="footer_title">About Us</h6>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore dolore
							magna aliqua.</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6 class="footer_title">Newsletter</h6>
						<p>Stay updated with our latest trends</p>
						<div id="mc_embed_signup">
							<form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
							 method="get" class="subscribe_form relative">
								<div class="input-group d-flex flex-row">
									<input name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address '"
									 required="" type="email">
									<button class="btn sub-btn"><span class="lnr lnr-arrow-right"></span></button>
								</div>
								<div class="mt-10 info"></div>
							</form>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 col-sm-6">
					<div class="single-footer-widget instafeed">
						<h6 class="footer_title">Instagram Feed</h6>
						<ul class="list instafeed d-flex flex-wrap">
							<li><img src="{% static 'app/img/i1.jpg' %}" alt=""></li>
							<li><img src="{% static 'app/img/i2.jpg' %}" alt=""></li>
							<li><img src="{% static 'app/img/i3.jpg' %}" alt=""></li>
							<li><img src="{% static 'app/img/i4.jpg' %}" alt=""></li>
							<li><img src="{% static 'app/img/i5.jpg' %}" alt=""></li>
							<li><img src="{% static 'app/img/i6.jpg' %}" alt=""></li>
							<li><img src="{% static 'app/img/i7.jpg' %}" alt=""></li>
							<li><img src="{% static 'app/img/i8.jpg' %}" alt=""></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-2 col-md-6 col-sm-6">
					<div class="single-footer-widget f_social_wd">
						<h6 class="footer_title">Follow Us</h6>
						<p>Let us be social</p>
						<div class="f_social">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-dribbble"></i></a>
							<a href="#"><i class="fa fa-behance"></i></a>
						</div>
					</div>
				</div>
			</div>
			<div class="row footer-bottom d-flex justify-content-between align-items-center">
				<p class="col-lg-12 footer-text text-center"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
			</div>
		</div>
	</footer>
	<!-- End footer Area -->

	<script src="{% static 'app/js/vendor/jquery-2.2.4.min.js' %}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
	 crossorigin="anonymous"></script>
	<script src="{% static 'app/js/vendor/bootstrap.min.js' %}"></script>
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
	<script src="{% static 'app/js/easing.min.js' %}"></script>
	<script src="{% static 'app/js/hoverIntent.js' %}"></script>
	<script src="{% static 'app/js/superfish.min.js' %}"></script>
	<script src="{% static 'app/js/jquery.ajaxchimp.min.js' %}"></script>
	<script src="{% static 'app/js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'app/js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'app/js/jquery.tabs.min.js' %}"></script>
	<script src="{% static 'app/js/jquery.nice-select.min.js' %}"></script>
	<script src="{% static 'app/js/waypoints.min.js' %}"></script>
	<script src="{% static 'app/js/mail-script.js' %}"></script>
	<script src="{% static 'app/js/main.js' %}"></script>
</body>

</html>

app/templates/app/category_details.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}


	<!-- Start main body Area -->
    <h2 class="text-center" style="color: #0c5460">{{ category.name }} Events</h2>
	<div class="main-body section-gap">
		<div class="container box_1170">
			<div class="row">
				<div class="col-lg-12 post-list">
					<!-- Start Post Area -->
					<section class="post-area">
						<div class="row">{% for events in event %}
                            {% if events.end_date > today %}
                            {% if events.approved == True %}
							<div class="col-lg-4 col-md-6">

								<div class="single-post-item">
									<div class="post-thumb">{% if events.flyer %}
										<img class="img-fluid" src="{{ events.flyer.url }}" alt="">
                                        {% endif %}
									</div>
									<div class="post-details">
										<h4><a href="{% url 'app:event_detail' events.slug %}">{{ events.title }}</a></h4>
										<p>{{ events.description|truncatechars:40 }}</p>
										<div class="blog-meta">
											<a href="#" class="m-gap">{% if events.start_date %}<span class="lnr lnr-calendar-full"></span>{{ events.start_date }}{% endif %}</a>
											<a href="#" class="m-gap">{% if events.end_date %}<span class="lnr lnr-calendar-full"></span>{{ events.end_date }}{% endif %}</a>
                                            <a href="#">{{ events.category }}</a>
										</div>
									</div>
								</div>
							</div>
                            {% endif %}
                            {% endif %}
                        {% endfor %}



							<div class="col-lg-12">
								<nav class="blog-pagination justify-content-center d-flex">
									<ul class="pagination">
										                            {% if users.has_other_pages %}

      {% if users.has_previous %}
        <a class="btn btn-outline-info mb-3" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-3" href="?page={{ users.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in users.paginator.page_range %}
        {% if users.number == num %}
          <a class="btn btn-info mb-3" href="?page={{ num }}">{{ num }}</a>
        {% elif num > users.number|add:'-3' and num < users.number|add:'3' %}
          <a class="btn btn-outline-info mb-3" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if users.has_next %}
        <a class="btn btn-outline-info mb-3" href="?page={{ users.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-3" href="?page={{ users.paginator.num_pages }}">Last</a>
      {% endif %}
        {% endif %}



									</ul>
								</nav>
							</div>
						</div>
					</section>
					<!-- Start Post Area -->
				</div>

				</div>
            </div>
            </div>
{% endblock content %}

app/templates/app/event_create.html
{% extends "app/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<br>
    <br>
    <br>
<div class="container" style="border-top:100px;">
    <div class="card">
        <div class="card-header">
            <h2>Create Event</h2>
        </div>
        <div class="card-body">
             {% crispy form %}
        </div>
    </div>
</div>
    <br>
{% endblock content %}

app/templates/app/event_detail.html
{% extends "app/base.html" %}
{% block content %}
{#<div class="card">#}
{#        <div class="card-header">#}
{#            <h1><b>{{ object.title }}</b></h1>#}
{#        </div>#}
{#        <div class="card-body">#}
{#        {% if object.author %}#}
{#                	<h4>#}
{#                        Author: {{ object.author.username }}</h4>#}
{##}
{#        {% endif %}#}
{##}
{#            	{% if object.description %}#}
{#    	<tr>#}
{#            <h4>Description</h4>#}
{#            <p>{{ object.description }}</p>#}
{#        </tr>#}
{#    	{% endif %}#}
{##}
{#        <table class="table">#}
{##}
{##}
{#        {% if object.tickettype_set %}#}
{#        {% for ticket in object.tickettype_set.all %}#}
{#        <tr>#}
{#            <th>Ticket Name: {{ticket.name}}</th>#}
{#            <td>Price: {{ticket.amount}}</td>#}
{#        </tr>#}
{#        {% endfor %}#}
{#        {% endif %}#}
{#        </table>#}
{#        <a class="btn btn-outline-info" href="{% url 'app:event_update' slug=object.slug %}">Update</a>#}
{#        <a class="btn btn-outline-danger" href="{% url 'app:event_delete' slug=object.slug %}">Delete</a>#}
{#        </div>#}
{#</div>#}
{##}

    <!-- Start banner Area -->
    <section class="banner-area relative">
        <div class="overlay overlay-bg"></div>
        <div class="container box_1170">
            <div class="row d-flex align-items-center justify-content-center">
                <div class="about-content col-lg-12">
                    <h1 class="text-white">
                        Event Details
                    </h1>
                    <p class="text-white link-nav"><a href="{% url 'app:home' %}">Home </a> <span class="lnr lnr-arrow-right"></span>
                        <a href="{% url 'app:category' object.category.slug %}">{{ object.category }}</a> <span class="lnr lnr-arrow-right"></span>
                        <a href="{% url 'app:event_detail' object.slug %}"> Event Details</a></p>
                </div>
            </div>
        </div>
    </section>
    <!-- End banner Area -->

    <!-- Blog Area -->
    <section class="blog_area section-gap single-post-area">
        <div class="container box_1170">
            <div class="row">
                <div class="col-lg-8">
                    <div class="main_blog_details">{% if object.flyer %}
                        <img class="img-fluid" src="{{ object.flyer.url }}" alt="">{% endif %}
                        <h4>{{ object.title }}</h4>
                        <div class="user_details">
                            <div class="float-left">
                                {% if object.category %}<a href="{% url 'app:category' object.category.slug %}">{{ object.category }}</a>{% endif %}
                            </div>
{#                            <div class="float-right">#}
{#                                <div class="media">#}
{#                                    <div class="media-body">#}
{#                                        <h5>Mark wiens</h5>#}
{#                                        <p>12 Dec, 2017 11:21 am</p>#}
{#                                    </div>#}
{#                                    <div class="d-flex">#}
{#                                        <img src="img/blog/user-img.jpg" alt="">#}
{#                                    </div>#}
{#                                </div>#}
{#                            </div>#}
                        </div>
                       <p>{{ object.description }}</p>
                        <blockquote class="blockquote">
                            <p class="mb-0">Venue: {{ object.venue }}</p>
                            <p class="mb-0">State: {{ object.state }} </p>
                            <p class="mb-0">Date: {% if object.start_date and object.start_date < object.end_date %}{{ object.start_date }} - {% endif %}{{ object.end_date }}</p>
                            <p class="mb-0">Time: {% if object.start_time %}{{ object.start_time }}{% endif %} - {% if object.end_time %}{{ object.end_time }} {% endif %} </p>
                        </blockquote>
                            {% if user.is_authenticated and user == object.author %}
                            <a class="btn btn-outline-info" href="{% url 'app:event_update' slug=object.slug %}">Update</a>
                            <a class="btn btn-outline-danger" href="{% url 'app:event_delete' slug=object.slug %}">Delete</a>
                    <br>{% endif %}
                                        <div>
            <ul class="messages">
                {% for message in messages %}
                <li class="{{ message.tags }}" style="color:Green;">{{ message }}</li>
                {% endfor %}
            </ul>
            </div>
                        <div class="news_d_footer">
                            <a href="#"><i class="lnr lnr lnr-heart"></i>Lily and 4 people like this</a>
                            <a class="justify-content-center ml-auto" href="#"><i class="lnr lnr lnr-bubble"></i>06
                                Comments</a>
                            <div class="news_socail ml-auto">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-pinterest"></i></a>
                                <a href="#"><i class="fa fa-rss"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="navigation-area">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                                <div class="thumb">
                                    <a href="#"><img class="img-fluid" src="img/blog/prev.jpg" alt=""></a>
                                </div>
                                <div class="arrow">
                                    <a href="#"><span class="lnr text-white lnr-arrow-left"></span></a>
                                </div>
                                <div class="detials">
                                    <p>Prev Post</p>
                                    <a href="#">
                                        <h4>A Discount Toner</h4>
                                    </a>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                                <div class="detials">
                                    <p>Next Post</p>
                                    <a href="#">
                                        <h4>Cartridge Is Better</h4>
                                    </a>
                                </div>
                                <div class="arrow">
                                    <a href="#"><span class="lnr text-white lnr-arrow-right"></span></a>
                                </div>
                                <div class="thumb">
                                    <a href="#"><img class="img-fluid" src="img/blog/next.jpg" alt=""></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


{% endblock content %}

app/templates/app/search.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}


	<!-- Start Post Silder Area -->

	<!-- Start main body Area -->
	<div class="main-body section-gap">
		<div class="container box_1170">
			<div class="row">
				<div class="col-lg-12 post-list">
					<!-- Start Post Area -->
					<section class="post-area">
                    {% if object in object_list >= 1 %} <h2>Showing Results For Related Search</h2>
{#                                {% else %}<h2>No Results For Your Search</h2>#}
                    {% endif %}
						<div class="row">{% for events in object_list %}
                            {% if events.approved == True %}
							<div class="col-lg-4 col-md-6">

								<div class="single-post-item">
									<div class="post-thumb">{% if events.flyer %}
										<img class="img-fluid" src="{{ events.flyer.url }}" alt="">
                                        {% endif %}
									</div>
									<div class="post-details">
										<h4><a href="{% url 'app:event_detail' events.slug %}">{{ events.title }}</a></h4>
										<p>{{ events.description|truncatechars:40 }}</p>
										<div class="blog-meta">
											{% if events.start_date %}<a href="#" class="m-gap"><span class="lnr lnr-calendar-full"></span>{{ events.start_date }}</a>{% endif %}
											{% if events.end_date %}<a href="#" class="m-gap"><span class="lnr lnr-calendar-full"></span>{{ events.end_date }}</a>{% endif %}
										        {% if events.category %}<a href="#">{{ events.category }}</a>{% endif %}
                                        </div>
									</div>
								</div>
							</div>
                            {% endif %}
{#                            {% endif %}#}
                        {% endfor %}



<div class="col-lg-12">
								<nav class="blog-pagination justify-content-center d-flex">
									<ul class="pagination">
{#										                            {% if is_paginated %}#}
{##}
{#      {% if page_obj.has_previous %}#}
{#        <a class="btn btn-outline-info mb-3" href="?page=1">First</a>#}
{#        <a class="btn btn-outline-info mb-3" href="?page={{ page_obj.previous_page_number }}">Previous</a>#}
{#      {% endif %}#}
{##}
{#      {% for num in page_obj.paginator.page_range %}#}
{#        {% if page_obj.number == num %}#}
{#          <a class="btn btn-info mb-3" href="?page={{ num }}">{{ num }}</a>#}
{#        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}#}
{#          <a class="btn btn-outline-info mb-3" href="?page={{ num }}">{{ num }}</a>#}
{#        {% endif %}#}
{#      {% endfor %}#}
{##}
{#      {% if page_obj.has_next %}#}
{#        <a class="btn btn-outline-info mb-3" href="?page={{ page_obj.next_page_number }}">Next</a>#}
{#        <a class="btn btn-outline-info mb-3" href="?page={{ page_obj.paginator.num_pages }}">Last</a>#}
{#      {% endif %}#}
{#        {% endif %}#}
									</ul>
								</nav>
							</div>
						</div>
					</section>
					<!-- Start Post Area -->
				</div>
            </div>
        </div>
    </div>
{% endblock content %}